Sprint 8. Filmorate
QuickHamster/java-filmorate pull request #1
Opened 2022-06-03 13:04 UTC by QuickHamster

Create Controllers films & users

2022-06-04 08:48 UTC, kukolev requested changes

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/FilmoreateApplication.java
> +	public static void main(String[] args) {
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +        //value = "/api/v1/films",  // T0D0 for production
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +    @GetMapping //("/list") // T0D0 for production
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/UserController.java
> +        //value = "/api/v1/users",  // T0D0 for production
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/UserController.java
> +    @GetMapping// ("/list") // T0D0 for production
Закомментированный код нужно удалить или раскомментировать и отладить. Оставлять закомментированный код это плохая практика, т.к. это только запутает программиста, который будет анализировать код.

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +        log.debug("Добавлен фильм: " + film);
При логировании лучше использовать возможности библиотеки и пользоваться плейсхолдерами `{}` вместо конкатенации строк. Лучше так: `log.warn("Some warning text for {}", val)` вместо `log.warn("Some warning text for " + val)`. Так код смотрится проще и не происходит лишняя конкатенация строк, если лог не будет напечатан.   

Аналогично нужно поправить везде в коде.

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +    private void filmOperation (boolean newFilm, Film film)  {
Нарушение кодстайла: Методы должны называться так, чтобы из названия можно было понять, за что отвечает метод. Так код будет понятней при анализе.

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +            if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
Объект LocalDate.of(1895, 12, 28) лучше сделать константой, чтобы не приходилось всякий раз создавать при валидации.

2022-06-04 08:48 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/UserController.java
> +    private void userOperation (boolean newUser, User user)  {
Нарушение кодстайла: Методы должны называться так, чтобы из названия можно было понять, за что отвечает метод. Так код будет понятней при анализе.

2022-06-04 08:48 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmoreate/FilmTests.java
> +	private static final FilmController filmController = new FilmController();
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

Также нужно поправить для каждого метода.

2022-06-04 08:48 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmoreate/FilmTests.java
> +		film = new Film(0L,"name", "description", LocalDate.now().minusYears(1),110);
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш  Ctrl + Alt + L и код автоматически отформатируется.

Также нужно поправить для каждого метода.

2022-06-04 08:48 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmoreate/UserTests.java
> +	private static final UserController userController = new UserController();
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш Ctrl + Alt + L и код автоматически отформатируется.

Также нужно поправить для каждого метода.

2022-06-04 08:48 UTC, kukolev commented on src/test/java/ru/yandex/practicum/filmoreate/UserTests.java
> +		user = new User(0L,"email@domain.ru", "login", "name", LocalDate.now().minusYears(1));
Нарушение кодстайла: Лишние отступы перед кодом. Советую в IDEA просто нажать комбинацию клавиш Ctrl + Alt + L и код автоматически отформатируется.

Также нужно поправить для каждого метода.

2022-06-05 09:22 UTC, QuickHamster commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +    private void filmOperation (boolean newFilm, Film film)  {
как лучше назвать метод по Вашему мнению? может filmProcessing?

2022-06-05 09:23 UTC, QuickHamster commented on src/main/java/ru/yandex/practicum/filmoreate/controller/UserController.java
> +    private void userOperation (boolean newUser, User user)  {
как лучше назвать метод по Вашему мнению? userProcessing подойдет?

2022-06-05 09:28 UTC, QuickHamster commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +        //value = "/api/v1/films",  // T0D0 for production
я хотел бы использовать эндпоинт такой как он есть в комментарии, но подумал, что проверяющему будет удобнее не переделывать тесты при проверке проекта. могу я оставить изначальный эндпоинт?

2022-06-05 09:29 UTC, QuickHamster commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +    @GetMapping //("/list") // T0D0 for production
я хотел бы использовать эндпоинт такой как он есть в комментарии, но подумал, что проверяющему будет удобнее не переделывать тесты при проверке проекта. могу я оставить изначальный эндпоинт?

2022-06-05 09:29 UTC, QuickHamster commented on src/main/java/ru/yandex/practicum/filmoreate/controller/UserController.java
> +        //value = "/api/v1/users",  // T0D0 for production
я хотел бы использовать эндпоинт такой как он есть в комментарии, но подумал, что проверяющему будет удобнее не переделывать тесты при проверке проекта. могу я оставить изначальный эндпоинт?

2022-06-05 22:51 UTC, kukolev requested changes

2022-06-05 22:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/FilmController.java
> +    private void filmProcessing(boolean newFilm, Film film) {
Нарушение кодстайла: Название метода лучше начинать с глагола, так назначение метода будет понятно сразу из названия. Нужно поправить. Как вариант метод можно переименовать в processFilm или еще как-то.

2022-06-05 22:51 UTC, kukolev commented on src/main/java/ru/yandex/practicum/filmoreate/controller/UserController.java
> +    private void userProcessing(boolean newUser, User user) {
Нарушение кодстайла: Название метода лучше начинать с глагола, так назначение метода будет понятно сразу из названия. Нужно поправить. Как вариант метод можно переименовать в processUser или еще как-то.

2022-06-06 15:45 UTC, kukolev approved these changes

2022-06-06 15:51 UTC, kukolev approved these changes

2022-06-07 06:16 UTC, merged